language: python
python:
  - "3.6"
# command to install dependencies
notifications:
  email: false
install:
  - pip install -r requirements.txt
# command to run tests
script: coverage run --rcfile=.coveragerc -m pytest 
after_success:
  - code-climate-test-reporter --token $CODECLIMATE_REPO_TOKEN
