language: python
python:
- '3.6'
notifications:
  email: false
install:
- pip install -r requirements.txt
script: coverage run --rcfile=.coveragerc -m pytest
after_success:
- codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN

deploy:
  provider: pypi
  user: "lucydot"
  password:
    secure: "afb38Rvw+2hjUYXOIqOzCHxDG+DR0IuNPTb61Q3aNqjibhUSJr0erRz0fS9wdYub1eiQ6G52BDxjapyxyZDuF+MJIsBmS0a1PjnK7Szzaz9yuzVfPxoibN7SEqc7usYFRjdRiVzlrh6nGADsXw/pRF8ja+SeWhs+f6jTpxDvD5HJ/l7ogCNvoGQj0rv+4kVQdOCsYWszzAz2E51sGYC48Tc+395BjqaAMxoLZBHxsDPl+3xAI8NYbv6EGg/WTmN3Efi/RtR1IGChXFAOqH18peAWx9jJPerx9Bczetbq+SjaWuE1J2dxUs/gDuzoS68okYwfIw18ZYP3yvDhO7VFNRF0ndBsZtU57TU6pnkUHXSbfg1hhdnnTX1Zl7qdVihIAxYjTLGOS5zrExDn0Tt6B15+jNxM///8Iy78InVmzlbJ0rD3YoP7pfWZYNbm4PmLIRiQ+CwDsimoN/lRnJeiATatJ3R37/wjXxg6NUAnhlHK4fuj/cki3GYwjB8SyRYGUnmlg75YOHyoVPvVwgBagvHoZTCSlWVJU24YLqQG/GXfqiK5L1iRksRQKLT4GBP68gyvWG9WUUo1zmArdEDe/8gKzUEl5cvxLIv/KuBjtNpgjrreXK2l+6WBLMfNskmTZS/X7zBlJ3lb6XU3y5sk5w85to5NpwxOvWnz6Xj3/0M="
  on: 
    tags: true
    branch: master
